# Generated by Django 6.0.7 on 2026-07-30 03:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='RA',
            new_name='ra',
        ),
    ]
