# Generated by Django 6.0.7 on 2026-08-02 00:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0002_rename_ra_student_ra'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='classroom',
        ),
        migrations.DeleteModel(
            name='Classroom',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
