# Generated by Django 6.0.7 on 2026-07-25 13:26

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Readings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('moment', models.CharField(choices=[('SNACK_MORNING', 'snack_morning'), ('LUNCH', 'lunch'), ('SNACK_AFTERNOON', 'snack_afternoon')], default='SNACK_MORNING', max_length=20)),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.student')),
            ],
            options={
                'db_table': 'readings',
            },
        ),
        migrations.CreateModel(
            name='Frequency',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('on_time', models.BooleanField(default=False)),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.student')),
                ('reading_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='presence.readings')),
            ],
            options={
                'db_table': 'frequencys',
            },
        ),
        migrations.CreateModel(
            name='RegisterSnack',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('moment', models.CharField(choices=[('SNACK_MORNING', 'snack_morning'), ('LUNCH', 'lunch'), ('SNACK_AFTERNOON', 'snack_afternoon')], default='SNACK_MORNING', max_length=20)),
                ('type_snack', models.CharField(choices=[('NORMAL', 'normal'), ('LITTLE', 'little')], default='NORMAL', max_length=200)),
                ('reading_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='presence.readings')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.student')),
            ],
            options={
                'db_table': 'register_snacks',
            },
        ),
    ]
