# Generated by Django 6.0.7 on 2026-07-18 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canteen', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailymenu',
            name='date',
            field=models.DateField(unique=True),
        ),
    ]
