# Generated by Django 6.0.7 on 2026-08-03 01:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('presence', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='frequency',
            old_name='reading_id',
            new_name='reading',
        ),
        migrations.RenameField(
            model_name='frequency',
            old_name='student_id',
            new_name='student',
        ),
        migrations.RenameField(
            model_name='readings',
            old_name='student_id',
            new_name='student',
        ),
        migrations.RenameField(
            model_name='registersnack',
            old_name='reading_id',
            new_name='reading',
        ),
        migrations.RenameField(
            model_name='registersnack',
            old_name='student_id',
            new_name='student',
        ),
    ]
