# Generated by Django 6.0.7 on 2026-08-02 00:36

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('school', '0005_school_time_send_snack_morning'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('moment', models.CharField(choices=[('SNACK_MORNING', 'snack_morning'), ('LUNCH', 'lunch'), ('SNACK_AFTERNOON', 'snack_afternoon')], max_length=20)),
                ('date', models.DateField()),
                ('number', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('ready', 'Enviada'), ('failed', 'Falha')], default='pending', max_length=10)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='school.school')),
            ],
            options={
                'db_table': 'whatsapp_message',
            },
        ),
    ]
