# Generated by Django 6.0.7 on 2026-07-10 00:31

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ('name', models.CharField(max_length=180)),
                ('time_closing_presence', models.TimeField()),
                ('time_send_lunch', models.TimeField()),
                ('time_send_snack_afternoon', models.TimeField()),
                ('number_whats', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deleted_at', models.DateTimeField(default=None, null=True)),
            ],
            options={
                'db_table': 'schools',
            },
        ),
    ]
