# Generated by Django 6.0.7 on 2026-07-10 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_manager'),
    ]

    operations = [
        migrations.RenameField(
            model_name='manager',
            old_name='school_id',
            new_name='school',
        ),
    ]
