# Generated by Django 6.0.7 on 2026-08-02 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0004_refreshtoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='time_send_snack_morning',
            field=models.TimeField(null=True),
        ),
    ]
