# Generated by Django 6.0.7 on 2026-08-15 03:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0005_school_time_send_snack_morning'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school',
            name='time_send_snack_morning',
        ),
    ]
