# Generated by Django 6.0.7 on 2026-08-16 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0006_remove_school_time_send_snack_morning'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='time_send_snack_morning',
            field=models.TimeField(null=True),
        ),
    ]
