# Generated by Django 6.0.7 on 2026-07-18 12:40

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('school', '0003_rename_school_id_manager_school'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyMenu',
            fields=[
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ('date', models.DateField()),
                ('main_course', models.TextField(max_length=1024)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                (
                    'manager',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to='school.manager',
                    ),
                ),
                (
                    'school',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to='school.school',
                    ),
                ),
            ],
            options={
                'db_table': 'daily_menu',
            },
        ),
    ]
