# Generated by Django 6.0.7 on 2026-07-23 15:55

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canteen', '0002_alter_dailymenu_date'),
        ('school', '0004_refreshtoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeftouversLunch',
            fields=[
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ('leftouvers_kg', models.IntegerField()),
                ('amount_students', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                (
                    'school',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to='school.school',
                    ),
                ),
                (
                    'user',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to='school.manager',
                    ),
                ),
            ],
            options={
                'db_table': 'leftouvers_lunch',
            },
        ),
    ]
