# Generated by Django 6.0.7 on 2026-08-17 19:09

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canteen', '0003_leftouverslunch'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('component', models.CharField(max_length=255)),
                ('daily_menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='canteen.dailymenu')),
            ],
            options={
                'db_table': 'ingredient',
            },
        ),
    ]
